= Back to the minefield
:revdate: 2023-04-05
:toc:
:toc-title:

// Last modified 20230405T1056+0200.

// English {{{1
== English

_Back to the minefield_ is a tribute to and a reinterpretation of Ian
Andrew's _Mined-Out_ game (1983), which was written in Sinclair BASIC
for ZX Spectrum.

This new version is being written in
http://programandala.net/en.program.vimclair_basic.html[Vimclair
BASIC] for ZX Spectrum 128.

The interface is multilingual: in English, Spanish, Esperanto and
Interlingue.

=== History of the repository

- 2020-12-04: the Git repository was converted to
  https://fossil-scm.org[Fossil], keeping
  http://github/programandala-net/back-to-the-minefield[GitHub as a
  mirror].
- 2023-04-05: the repository was converted to
  https://mercurial-scm.org[Mercurial], enabling a better interaction
  with GitHub.

// Español {{{1
== Español

_Back to the minefield_ (Regreso al campo de minas) es un homenaje y
una reinterpretación del juego _Mined-Out_ de Ian Andrew (1983), que
fue escrito en Sinclair BASIC para ZX Spectrum.

Esta nueva versión está siendo escrita en
http://programandala.net/es.programa.vimclair_basic.html[Vimclair
BASIC] para ZX Spectrum 128.

La interfaz es multilingüe: en inglés, español, esperanto e
interlingüe.

=== Historia del repositorio

- 2020-12-04: el repositorio de Git fue convertido a
  https://fossil-scm.org[Fossil], dejando
  http://github/programandala-net/back-to-the-minefield[GitHub como
  réplica].
- 2023-04-05: el repositorio fue convertido a
  https://mercurial-scm.org[Mercurial], posibilitando una mejor
  interacción con GitHub.

// Esperanto {{{1
== Esperanto

_Back to the minefield_ (Reveno al la min-kampo) estas omaĝo kaj
reinterpreto je la ludo _Mined-Out_ de Ian Andrew (1983), kiu estis
verkita en Sinclair BASIC por ZX Spectrum. 

Ĉi nova version estas programata en
http://programandala.net/es.programa.vimclair_basic.html[Vimclair
BASIC] por ZX Spectrum 128.

La interfaco estas plurlingva: in angla, hispana, Esperanto kaj
Interlingveo.

=== Historio de la deponejo

- 2020-12-04: la Git-deponejo estis konvertita al
  https://fossil-scm.org[Fossil], konservante
  http://github/programandala-net/back-to-the-minefield[GitHub kiel
  kopion].
- 2023-04-05: la deponejo estis konvertita al
  https://mercurial-scm.org[Mercurial], ebligante pli bonan interagon
  kun GitHub.

// Interlingue/Occidental {{{1
== Interlingue/Occidental

_Back to the minefield_ (Revenida al camp de mines) es un tribute e un
reinterpretation ye li lude _Mined-Out_ de Ian Andrew (1983), quel
esset programat in Sinclair BASIC por ZX Spectrum.

Ti nov version es programat in
http://programandala.net/es.programa.vimclair_basic.html[Vimclair
BASIC] por ZX Spectrum 128.

Li interfacie es plurilingual: in anglesi, hispan, Esperanto e
Interlingue.

=== Historie del depositoria

- 2020-12-04: li depositoria de Git esset convertet a
  https://fossil-scm.org[Fossil], conservante
  http://github/programandala-net/back-to-the-minefield[GitHub quam un
  copie].
- 2023-04-05: li depositoria esset convertet a
  https://mercurial-scm.org[Mercurial], possibilisante un melior
  interaction con GitHub.
