= Back to the minefield
:revdate: 2020-12-04
:toc:
:toc-title:

// English {{{1
== English

_Back to the minefield_ is a tribute to and a reinterpretation of Ian
Andrew's _Mined-Out_ game (1983), which was written in Sinclair BASIC
for ZX Spectrum.

This new version is being written in
http://programandala.net/en.program.vimclair_basic.html[Vimclair
BASIC] for ZX Spectrum 128.

The interface is multilingual: in English, Spanish, Esperanto and
Interlingue.

Note: On 2020-12-04 the Git repository was converted to
http://fossil-scm.org[Fossil], and since then GitHub is used only as a
copy.

// Español {{{1
== Español

_Back to the minefield_ (Regreso al campo de minas) es un homenaje y
una reinterpretación del juego _Mined-Out_ de Ian Andrew (1983), que
fue escrito en Sinclair BASIC para ZX Spectrum.

Esta nueva versión está siendo escrita en
http://programandala.net/es.programa.vimclair_basic.html[Vimclair
BASIC] para ZX Spectrum 128.

La interfaz es multilingüe: en inglés, español, esperanto e
interlingüe.

Nota: En 2020-12-04 el repositorio Git fue convertido a
http://fossil-scm.org[Fossil], y desde entonces GitHub se usa solo
como una copia.

// Esperanto {{{1
== Esperanto

_Back to the minefield_ (Reveno al la min-kampo) estas omaĝo kaj
reinterpreto je la ludo _Mined-Out_ de Ian Andrew (1983), kiu estis
verkita en Sinclair BASIC por ZX Spectrum. 

Ĉi nova version estas programata en
http://programandala.net/es.programa.vimclair_basic.html[Vimclair
BASIC] por ZX Spectrum 128.

La interfaco estas plurlingva: in angla, hispana, Esperanto kaj
Interlingveo.

Noto: Je 2020-12-04 la Git-deponejo estis konvertita al
http://fossil-scm.org[Fossil], kaj de tiam 
GitHub estas uzata nur kiel kopion.

// Interlingue {{{1
== Interlingue

_Back to the minefield_ (Revenida al camp de mines) es un tribute e un
reinterpretation ye li lude _Mined-Out_ de Ian Andrew (1983), quel
esset programat in Sinclair BASIC por ZX Spectrum.

Ti nov version es programat in
http://programandala.net/es.programa.vimclair_basic.html[Vimclair
BASIC] por ZX Spectrum 128.

Li interfacie es plurilingual: in anglesi, hispan, Esperanto e
Interlingue.

Note: In 2020-12-04 li depositoria de Git esset convertet a
http://fossil-scm.org[Fossil], e desde tande GitHib es usat solmen
quam un copie.
